### ISSUE TITLE
Crashes scripts every time I try to use it

### ISSUE THREAD

**Issue by dumptruckman** [defamai/Roll20#1]
This is the output from the api console

"[MM]: Importing Monsters..."
"[MM]: Processing 1 lines of text..."
{"name":"Monster Import","notes":1430686182343,"gmnotes":1430686660699,"inplayerjournals":"","archived":false,"controlledby":"","_type":"handout","_id":"-JoQXA_6LMH7QwSvCPQ9","avatar":""}

/home/symbly/www/d20-api-server/node_modules/firebase/lib/firebase-node.js:1
orts, require, module, __filename, __dirname) { function g(a){throw a;}var j=v
                                                                    ^
TypeError: Object  has no method 'capitalizeFirstLetter'
    at evalmachine.<anonymous>:1047:48
    at eval (

The monster I've tried to import was http://www.d20pfsrd.com/bestiary/monster-listings/magical-beasts/hydra

**Comment by cstufflebeam** [comment]
Hello!

You're missing a common file which provides a few utility functions used by this, and other scripts of mine. You can obtain it from here:

https://github.com/defamai/Roll20/blob/master/common/utility.js

Furthermore, the regular expressions that this script uses are set up to parse content from D&D 3.5, and is confirmed working with the SRD, as well as the Monster Manual. Pathfinder content is formatted differently, and will not be parsed successfully by this script.

**Comment by dumptruckman** [comment]
Now it is complaining about missing mandatory field hitdie... Most stat blocks simply label `hp 12 (2d8+3)`. Is there some special change that needs to happen?

**Comment by cstufflebeam** [comment]
Like I said before, this script is set up to parse D&D 3.5 material - Pathfinder material will not work without regex changes, as it is commonly formatted differently.

**Comment by dumptruckman** [comment]
Oh! Sorry, I missed that part. Carry on!
